#ifndef SEARCH_SERVER_BENCHMARKING_BENCHMARKING_HPP_
#define SEARCH_SERVER_BENCHMARKING_BENCHMARKING_HPP_

#include <benchmarking/log_duration.hpp>
#include <runner/runner.hpp>

#endif // SEARCH_SERVER_BENCHMARKING_BENCHMARKING_HPP_
